In [3]:
import cv2
import numpy as np
import pandas as pd

In [5]:
face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")
eyes_cascade = cv2.CascadeClassifier("./Train/third-party/haarcascade_eye.xml")
nose_cascade = cv2.CascadeClassifier("./Train/third-party/haarcascade_mcs_nose.xml")

img = cv2.imread('./Test/Before.png')
mustache = cv2.imread('./Train/mustache.png',-1)
glasses = cv2.imread('./Train/glasses.png',-1)

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
img = cv2.cvtColor(img, cv2.COLOR_BGR2BGRA)#make picture gray

In [6]:
faces = face_cascade.detectMultiScale(gray, 1.3, 5)

for (x,y,w,h) in faces:
	roi_gray = gray[y:y+h, x:x+w]
	roi_color = img[y:y+h, x:x+w]
	#cv2.rectangle(img,(x,y),(x+w,y+h),(255,255,0),2)


	eyes = eyes_cascade.detectMultiScale(roi_gray,1.3,5)
	el = []
	for(ex,ey,ew,eh) in eyes:
		#cv2.rectangle(roi_color,(ex, ey), (ex+ew, ey+eh),(0,255,0),3)
		el.append((ex,ey,ew,eh))
		roi_eyes = roi_gray[ey:ey+eh, ex:ex+w]
	
	el = sorted(el , key = lambda a : a[0])
	#print(el)	
	ewf = el[1][0] + el[1][2] - el[0][0]
	ehf = el[1][1] + el[1][3] - el[0][1]

	#print(ewf,ehf)
	glasses2 = cv2.resize(glasses.copy(),(int(1.2*ewf),int(2*ehf)))
	#print(glasses2.shape)
	gw, gh, gc = glasses2.shape
	for i in range(0,gw):
		for j in range(0,gh):
			if glasses2[i,j][3] != 0:
				roi_color[int((el[0][1]+el[1][1])/3)+i, int((h-gh)/2)+j] = glasses2[i, j]



	nose = nose_cascade.detectMultiScale(roi_gray, scaleFactor=1.5, minNeighbors=5)
	for (nx, ny, nw, nh) in nose:
		#cv2.rectangle(roi_color, (nx, ny), (nx + nw, ny + nh), (255, 0, 0), 3)
		roi_nose = roi_gray[ny: ny+nh, nx:nx+nw]
		mustache2 = cv2.resize(mustache.copy(),(nw,int(0.5*ny)))

		mw, mh, mc = mustache2.shape
		for i in range(0,mw):
			for j in range(0,mh):
				if mustache2[i,j][3] != 0:
					roi_color[ny + int(nh/2) + i, nx+j] = mustache2[i,j]

 


In [ ]:
#Display resulting frame
img = cv2.cvtColor(img, cv2.COLOR_BGRA2BGR)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

cv2.imshow('Image',img)



img = np.reshape(img , (-1,3))
print((img))


cv2.waitKey(0)



cv2.destroyAllWindows()

[[219 202 180]
 [220 203 181]
 [219 202 180]
 ...
 [ 19  13  13]
 [ 21  15  15]
 [ 22  15  15]]


In [ ]:
dfa = pd.DataFrame({"Prediction (R, G , B)" : list(img)})

In [ ]:
dfa

In [7]:
dfa.to_csv('ans.csv',index = False)

In [8]:
df= pd.read_csv("./ans.csv")
df

Prediction (R, G , B)
0              [219 202 180]
1              [220 203 181]
2              [219 202 180]
3              [220 203 181]
4              [219 202 180]
5              [218 201 179]
6              [216 199 177]
7              [216 199 177]
8              [216 199 177]
9              [217 200 178]
10             [218 201 179]
11             [219 202 180]
12             [219 202 180]
13             [219 202 180]
14             [220 203 181]
15             [220 203 181]
16             [219 202 180]
17             [220 203 181]
18             [220 203 181]
19             [220 203 181]
20             [218 201 179]
21             [219 202 180]
22             [220 203 181]
23             [219 202 180]
24             [219 202 180]
25             [219 202 180]
26             [218 201 179]
27             [218 201 179]
28             [219 202 180]
29             [220 203 181]
...                      ...
182815               [8 4 5]
182816            [10  6  7]
182817            [12  8  9]
182818            [14  9 10]
182819            [19 13 15]
182820            [27 21 23]
182821            [27 21 23]
182822            [19 13 15]
182823            [16  9 11]
182824            [16  9 11]
182825            [12  6  8]
182826            [10  4  6]
182827            [13  6  8]
182828            [16 10 10]
182829            [11  4  4]
182830               [9 3 3]
182831            [16 10 10]
182832            [15  8  8]
182833            [12  5  5]
182834            [18 11 11]
182835            [16  9  9]
182836            [15  9  9]
182837            [15  9  9]
182838            [19 13 13]
182839            [20 14 14]
182840            [23 17 17]
182841            [20 14 14]
182842            [19 13 13]
182843            [21 15 15]
182844            [22 15 15]

[182845 rows x 1 columns]